In [10]:
import numpy as np
import pandas as pd
import random
import tensorflow as tf
import os
from pandastable import Table, TableModel
from tkinter import *
from explainerdashboard import ClassifierExplainer, ExplainerDashboard


## pycaret
from pycaret.regression import *

## FinBERT
from transformers import BertTokenizer, BertForSequenceClassification
from transformers import pipeline

## SDV
from sdv.metadata import SingleTableMetadata
from sdv.single_table import GaussianCopulaSynthesizer
from sdv.sampling import Condition
from sdv.evaluation.single_table import evaluate_quality
from sdv.evaluation.single_table import run_diagnostic
from sdv.evaluation.single_table import get_column_plot
from sdv.evaluation.single_table import get_column_pair_plot
from sdv.sequential import PARSynthesizer
from sdv.sampling import Condition
from sdmetrics.reports.single_table import QualityReport
from sdmetrics.reports.utils import get_column_plot
from sdmetrics.reports.utils import get_column_plot

## LSTM
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense, LSTM, Dropout
from sklearn.metrics import *
from sklearn.model_selection import train_test_split
from keras.callbacks import EarlyStopping

import socket

seed_num = 42
np.random.seed(seed_num)
random.seed(seed_num)
tf.random.set_seed(seed_num)
tf.keras.utils.set_random_seed(seed_num)
os.chdir('/Users/hiksang/Desktop/Proj/DF/EWS/data')  # 추후 DB로 변환

In [4]:
df = pd.read_csv('KVALL.WD.csv')


def make_pipeline():    
    finbert = BertForSequenceClassification.from_pretrained('yiyanghkust/finbert-tone',num_labels=3)
    tokenizer = BertTokenizer.from_pretrained('yiyanghkust/finbert-tone')
    nlp = pipeline("sentiment-analysis", model=finbert, tokenizer=tokenizer)
    return nlp

def classification_text(text):
    result = nlp()
    
feature_col = df.iloc[:,4:].columns
feature_list = feature_col.to_list()
feature_cols = feature_list[1:]
feature_target = [feature_list[0]]
feature_bank = feature_list + ['bank.code']
feature_all = feature_bank + ['date']
print(feature_target)
print(feature_list)
print(feature_cols)

['KV001']
['KV001', 'KV002', 'KV003', 'KV004', 'KV005', 'KV006', 'KV007', 'KV008', 'KV009', 'KV010', 'KV011', 'KV012', 'KV013', 'KV014', 'KV015', 'KV016', 'KV017', 'KV018']
['KV002', 'KV003', 'KV004', 'KV005', 'KV006', 'KV007', 'KV008', 'KV009', 'KV010', 'KV011', 'KV012', 'KV013', 'KV014', 'KV015', 'KV016', 'KV017', 'KV018']

# PreProcess

In [5]:
def prep_data(df, feature_col):
    df = df[feature_col]
    df = df.replace([np.inf, -np.inf], np.nan)  # "inf" 값을 NaN으로 대체
    df = df.dropna()
    return df


def fss_date(df, feature_col, bank_name): # 
    df['date'] = pd.to_datetime(df['year.code'].astype(str) + df['month.code'].astype(str), format='%Y%m') 

    df = df[feature_col]
    df = df.replace([np.inf, -np.inf], np.nan)  # "inf" 값을 NaN으로 대체
    df = df.dropna()
    print(df)
    df = df[df['bank.code'] == bank_name]
    df = df.drop(columns=['bank.code'])

    
    return df


def lstm_train_test(prep_df):
    feature_cols = ['KV002','KV003','KV004','KV005','KV006','KV007','KV008','KV009','KV010',
               'KV011', 'KV012', 'KV013','KV014','KV015','KV016','KV017','KV018']
    label_col = ['KV001']

    feature_df = pd.DataFrame(prep_df, columns=feature_cols)
    label_df = pd.DataFrame(prep_df, columns=label_col)

    feature_df = feature_df.to_numpy()
    label_df = label_df.to_numpy()
    
    x_train, x_test, y_train, y_test = train_test_split(feature_df, label_df, test_size=0.4, shuffle=False, random_state=42)
    x_val, x_test, y_val, y_test = train_test_split(x_test, y_test, test_size=0.5, shuffle=False, random_state=42)
    print(len(x_train), len(x_val), len(x_test))
    return x_train.reshape(-1,1,17), x_val.reshape(-1,1,17), x_test.reshape(-1,1,17), y_train.reshape(-1,1,1), y_val.reshape(-1,1,1), y_test.reshape(-1,1,1)


df_ml = prep_data(df, feature_bank)
df_lstm = fss_date(df, feature_all, 'BANK #1')
x_train, x_val, x_test, y_train, y_val, y_test = lstm_train_test(df_lstm)

    

    

print(len(df_lstm))

        KV001      KV002      KV003     KV004     KV005     KV006      KV007  \
15   7.490800  11.230069  12.892386  0.647280 -8.069694  4.787695  29.034507
16   7.381399  11.509397  12.977475  0.495335 -1.847013  0.894125  29.547321
17   7.331138  11.553702  13.024878  0.820232 -3.768500  2.526414  29.872508
18   7.403061  11.589960  13.047304  1.212506 -5.585090  4.531546  31.057246
19   6.973216   9.064114  10.816283  1.009559 -7.276591  3.756003  30.998928
..        ...        ...        ...       ...       ...       ...        ...
879  7.382142  10.968299  13.063094  1.878980 -3.793386  0.956893  34.626846
880  7.059718  10.815314  12.733773  0.526592 -1.247132  4.581053  34.833039
881  6.858891  10.665785  12.534142  1.030550 -2.661936  2.664026  34.366872
882  6.840320  10.670107  12.508762  1.514801 -4.543245  1.043397  34.195223
883  6.956038  10.731233  12.599827  1.585924 -7.251555 -1.389545  33.836448

        KV008      KV009     KV010       KV011     KV012     KV013     KV014  \
15  -1.752446  31.547586  4.417577   96.510839  3.108897  3.328412 -2.681132
16   2.671965  32.670500  4.259731   96.682896  0.505023  0.182472  0.312864
17  -0.054115  32.198713  4.223614   95.086961  1.079153  0.713768  0.106465
18   1.154366  32.394182  4.220511   96.365554  1.488744  1.076029  0.136478
19   0.018562  31.168660  3.382929   94.943455  1.498435  1.453273 -0.443714
..        ...        ...       ...         ...       ...       ...       ...
879  1.737244  40.267279  0.986555   99.344673  1.430985  0.555365  1.323615
880  2.200539  39.585022  1.014208   98.568201 -0.531786  0.079552  0.447040
881  2.805829  39.109204  0.898691   96.192528 -1.478574  0.318522  0.712028
882  2.198896  39.358875  0.957222  101.278477 -2.278478  0.369362  1.145439
883  1.244069  39.986061  1.032089   97.976613 -0.277044  0.731703  0.854221

         KV015      KV016      KV017       KV018 bank.code       date
15  -25.238069  24.506420  96.638808   -9.084048   BANK #1 2013-12-01
16    4.506754  21.528201   5.391553    1.164575   BANK #1 2014-03-01
17   28.660505  18.974260  21.322032   15.309219   BANK #1 2014-06-01
18   45.932303  21.164867  33.418492   42.007045   BANK #1 2014-09-01
19  -20.013017  27.607346  45.049917   83.792845   BANK #1 2014-12-01
..         ...        ...        ...         ...       ...        ...
879  86.837924  64.717433  19.230542  358.380380  BANK #17 2021-12-01
880 -61.573850   0.621701   2.771032   51.347226  BANK #17 2022-03-01
881  -3.494356  62.240823  10.946595  186.869317  BANK #17 2022-06-01
882  50.944604  27.264489  12.630425  174.716676  BANK #17 2022-09-01
883  83.424289  29.947053  24.758217  192.099002  BANK #17 2022-12-01

[567 rows x 20 columns]
21 7 8
36

# AutoML

In [14]:

def make_localhost(port):    
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    s.connect(('8.8.8.8', 1))
    local_ip_address = s.getsockname()[0] 
    return f'http://{local_ip_address}:{port}'
    
def auto_ml(df, target, bank_name):
    df = df[df['bank.code'] == bank_name]
    df = df.drop(columns=['bank.code'])
    model = setup(df, target = target, session_id= 42)
    best = compare_models()
    
    linear_reg = create_model('lr', cross_validation=True)
    ridge_reg = create_model('ridge', cross_validation=True)
    xgb = create_model('xgboost', cross_validation = True)
    lgb = create_model('lightgbm', cross_validation = True)
    
    linear_port = 8000
#     XGBoost_port = 8010
#     lightGBM_port =8020
#     GBM_port =8030
#     ridge_port = 8040    
    
#     ## dashboard of linear
    dashboard(linear_reg, run_kwargs={'port':linear_port})#, 'host':'0.0.0.0'})
#     linear_address = make_localhost(linear_port)
    
#     ## dashboard of ridge
#     dashboard(ridge_reg, run_kwargs={'port':ridge_port})#, 'host':'0.0.0.0'})
#     ridge_address = make_localhost(linear_port)
    
#     ## dashboard of xgb
#     dashboard(xgb, run_kwargs={'port':XGBoost_port})#, 'host':'0.0.0.0'})
#     xgb_address = make_localhost(linear_port)
    
#     ## dashboard of lightgbm
#     dashboard(lgb, run_kwargs={'port':lightGBM_port})#, 'host':'0.0.0.0'})
#     lightgbbm_address = make_localhost(linear_port)
    
#     address_dict = {'lr' : linear_address, 'ridge': ridge_address, 'xgboost' : xgb_address, 'lightgbm' : lightgbbm_address}
    return linear_reg

def auto_ml_all(df, target):
    df = df.drop(columns=['bank.code'])
    
    model = setup(df, target = target, session_id= 42)
    best = compare_models()
    
    linear_reg = create_model('lr', cross_validation=True)
    ridge_reg = create_model('ridge', cross_validation=True)
    xgb = create_model('xgboost', cross_validation = True)
    lgb = create_model('lightgbm', cross_validation = True)
    
#     dashboard(linear_reg)
#     dashboard(xgb)
    
estm = auto_ml(df_ml, "KV001", 'BANK #1')

print(len(df_ml))
# auto_ml_all(df_ml, "KV001")

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

WARNING: For shap='linear', shap interaction values can unfortunately not be calculated!
Warning: shap values for shap.LinearExplainer get calculated against X_background, but paramater X_background=None, so using X instead
Generating self.shap_explainer = shap.LinearExplainer(modelX)...
Building ExplainerDashboard..
Detected notebook environment, consider setting mode='external', mode='inline' or mode='jupyterlab' to keep the notebook interactive while the dashboard is running...
For this type of model and model_output interactions don't work, so setting shap_interaction=False...
The explainer object has no decision_trees property. so setting decision_trees=False...
Generating layout...
Calculating shap values...
Calculating predictions...
Calculating residuals...
Calculating absolute residuals...
Calculating dependencies...
Calculating importances...
Reminder: you can store the explainer (including calculated dependencies) with explainer.dump('explainer.joblib') and reload with e.g. ClassifierExplainer.from_file('explainer.joblib')
Registering callbacks...
Starting ExplainerDashboard on http://172.16.21.139:8000

567

# dashboard to html

In [26]:
from explainerdashboard import ExplainerDashboard, RegressionExplainer


df = df_ml[df['bank.code'] == "BANK #1"]
df_ml = df.drop(columns=['bank.code'])

model = setup(df_ml, target =  "KV001") ## 추후 shuffle False
best = compare_models()
linear_reg = create_model('lr', cross_validation=True)
X_test_df = model.X_test_transformed.copy()
y_test = model.y_test_transformed
print(x_train)
X_test_df.columns = [col.replace(".", "__").replace("{", "__").replace("}", "__") for col in X_test_df.columns]
explainer = RegressionExplainer(linear_reg, X_test_df, y_test)
ExplainerDashboard(explainer, mode='dash').run()

# html_linear = ExplainerDashboard(explainer, mode='dash').save_html()




# from explainerdashboard import ExplainerDashboard, RegressionExplainer

#         # Replaceing chars which dash doesnt accept for column name `.` , `{`, `}`
# X_test_df = self.X_test_transformed.copy()
# X_test_df.columns = [
#             col.replace(".", "__").replace("{", "__").replace("}", "__")
#             for col in X_test_df.columns
#         ]
# explainer = RegressionExplainer(
#             estimator, X_test_df, self.y_test_transformed, **kwargs
#         )
# return ExplainerDashboard(
#     explainer, mode=display_format, **dashboard_kwargs
#         ).run(**run_kwargs)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

         KV002      KV003     KV004     KV005      KV006      KV007     KV008  \
671  15.522093  15.820181  2.206114 -0.419899   0.172194  36.593109  4.545916
23    8.613658  10.604945  1.351652 -5.244090   3.792024  33.337486 -1.483327
860  10.878238  11.920766  0.492949 -0.806683  16.423546  20.478924  3.716913
85   16.644384  16.644384  0.850648  4.768416  -0.321974  35.557476  1.828264
17   11.553701  13.024878  0.820232 -3.768500   2.526414  29.872509 -0.054115
..         ...        ...       ...       ...        ...        ...       ...
46   13.767385  15.085279  1.844785 -1.519952   1.873275  34.837662  3.526832
708  15.466281  15.825948  0.711049 -0.977346   1.252268  33.362732  0.644348
125  17.954687  17.954687  1.486087 -3.248996  -0.757332  27.622940 -1.197789
863  10.994670  12.034121  2.441579 -3.552291   9.403339  24.727489  0.324836
247  12.861914  14.140787  2.683846 -4.521680   3.211112  23.172119  0.102454

         KV009     KV010       KV011  ...  bank.code_BANK #15  \
671  31.095913  0.524116   95.968063  ...                 0.0
23   31.317339  2.429190   95.323639  ...                 0.0
860  47.968224  1.924939  143.617661  ...                 0.0
85   11.260240  1.567031   83.123207  ...                 0.0
17   32.198711  4.223614   95.086960  ...                 0.0
..         ...       ...         ...  ...                 ...
46   30.673084  0.833139   91.322243  ...                 0.0
708  31.406397  1.074929   96.378120  ...                 0.0
125  13.814544  4.201055   78.114891  ...                 0.0
863  44.994320  2.824695  130.593582  ...                 0.0
247  48.086262  2.300460  100.000435  ...                 0.0

     bank.code_BANK #9  bank.code_BANK #5  bank.code_BANK #2  \
671                0.0                0.0                0.0
23                 0.0                0.0                0.0
860                0.0                0.0                0.0
85                 0.0                0.0                1.0
17                 0.0                0.0                0.0
..                 ...                ...                ...
46                 0.0                0.0                0.0
708                0.0                0.0                0.0
125                0.0                0.0                0.0
863                0.0                0.0                0.0
247                0.0                1.0                0.0

     bank.code_BANK #17  bank.code_BANK #11  bank.code_BANK #7  \
671                 0.0                 0.0                0.0
23                  0.0                 0.0                0.0
860                 1.0                 0.0                0.0
85                  0.0                 0.0                0.0
17                  0.0                 0.0                0.0
..                  ...                 ...                ...
46                  0.0                 0.0                0.0
708                 0.0                 0.0                0.0
125                 0.0                 0.0                0.0
863                 1.0                 0.0                0.0
247                 0.0                 0.0                0.0

     bank.code_BANK #3  bank.code_BANK #16  bank.code_BANK #13
671                0.0                 0.0                 1.0
23                 0.0                 0.0                 0.0
860                0.0                 0.0                 0.0
85                 0.0                 0.0                 0.0
17                 0.0                 0.0                 0.0
..                 ...                 ...                 ...
46                 0.0                 0.0                 0.0
708                0.0                 0.0                 0.0
125                1.0                 0.0                 0.0
863                0.0                 0.0                 0.0
247                0.0                 0.0                 0.0

[171 rows x 33 columns]
WARNING: For shap='linear', shap interaction values can unfortunately not be calculated!
Warning: shap values for shap.LinearExplainer get calculated against X_background, but paramater X_background=None, so using X instead
Generating self.shap_explainer = shap.LinearExplainer(modelX)...
Building ExplainerDashboard..
Detected notebook environment, consider setting mode='external', mode='inline' or mode='jupyterlab' to keep the notebook interactive while the dashboard is running...
For this type of model and model_output interactions don't work, so setting shap_interaction=False...
The explainer object has no decision_trees property. so setting decision_trees=False...
Generating layout...
Calculating shap values...
Calculating predictions...
Calculating residuals...
Calculating absolute residuals...
Calculating dependencies...
Calculating importances...
Reminder: you can store the explainer (including calculated dependencies) with explainer.dump('explainer.joblib') and reload with e.g. ClassifierExplainer.from_file('explainer.joblib')
Registering callbacks...
Starting ExplainerDashboard on http://172.16.21.139:8050

In [32]:
linear_dash = ExplainerDashboard(explainer, mode='dash')
linear_dash.save_html('ht.html')

Building ExplainerDashboard..
Detected notebook environment, consider setting mode='external', mode='inline' or mode='jupyterlab' to keep the notebook interactive while the dashboard is running...
For this type of model and model_output interactions don't work, so setting shap_interaction=False...
The explainer object has no decision_trees property. so setting decision_trees=False...
Generating layout...
Calculating dependencies...
Reminder: you can store the explainer (including calculated dependencies) with explainer.dump('explainer.joblib') and reload with e.g. ClassifierExplainer.from_file('explainer.joblib')
Registering callbacks...

In [107]:
x_train, x_val, x_test, y_train, y_val, y_test

(array([[[ 1.12300695e+01,  1.28923864e+01,  6.47280076e-01,
          -8.06969403e+00,  4.78769478e+00,  2.90345074e+01,
          -1.75244558e+00,  3.15475865e+01,  4.41757700e+00,
           9.65108389e+01,  3.10889742e+00,  3.32841217e+00,
          -2.68113209e+00, -2.52380692e+01,  2.45064197e+01,
           9.66388078e+01, -9.08404794e+00]],

        [[ 1.15093966e+01,  1.29774750e+01,  4.95335491e-01,
          -1.84701326e+00,  8.94125058e-01,  2.95473212e+01,
           2.67196459e+00,  3.26705002e+01,  4.25973062e+00,
           9.66828956e+01,  5.05022814e-01,  1.82471807e-01,
           3.12863684e-01,  4.50675406e+00,  2.15282009e+01,
           5.39155308e+00,  1.16457547e+00]],

        [[ 1.15537018e+01,  1.30248777e+01,  8.20232407e-01,
          -3.76849963e+00,  2.52641359e+00,  2.98725083e+01,
          -5.41154602e-02,  3.21987129e+01,  4.22361441e+00,
           9.50869614e+01,  1.07915286e+00,  7.13767725e-01,
           1.06464682e-01,  2.86605053e+01,  1.89742604e+01,
           2.13220323e+01,  1.53092192e+01]],

        [[ 1.15899599e+01,  1.30473038e+01,  1.21250637e+00,
          -5.58508996e+00,  4.53154582e+00,  3.10572455e+01,
           1.15436569e+00,  3.23941817e+01,  4.22051112e+00,
           9.63655537e+01,  1.48874401e+00,  1.07602885e+00,
           1.36477520e-01,  4.59323026e+01,  2.11648674e+01,
           3.34184921e+01,  4.20070446e+01]],

        [[ 9.06411377e+00,  1.08162833e+01,  1.00955944e+00,
          -7.27659121e+00,  3.75600286e+00,  3.09989283e+01,
           1.85615940e-02,  3.11686599e+01,  3.38292918e+00,
           9.49434549e+01,  1.49843482e+00,  1.45327336e+00,
          -4.43713917e-01, -2.00130169e+01,  2.76073464e+01,
           4.50499167e+01,  8.37928450e+01]],

        [[ 8.86519146e+00,  1.03803288e+01,  3.71955151e-01,
          -1.50618402e+00,  2.74805570e+00,  3.07613236e+01,
           4.73333542e+00,  3.15273734e+01,  3.12064244e+00,
           9.74131716e+01,  3.18811412e-01,  3.48331456e-01,
           2.36236953e-02,  3.46689379e+01,  1.89233897e+01,
           1.07151366e+01,  2.63163755e+01]],

        [[ 8.88116170e+00,  1.09200258e+01,  6.57388205e-01,
          -2.88321194e+00,  3.37035531e+00,  3.10325642e+01,
           6.89424808e-01,  3.09804903e+01,  2.88593618e+00,
           9.52264699e+01,  8.00921898e-01,  1.02907388e+00,
          -3.71685672e-01,  6.75537264e+01,  1.56589587e+01,
           3.19348011e+01,  1.09153150e+02]],

        [[ 8.49944528e+00,  1.04448278e+01,  1.01883110e+00,
          -4.04314578e+00,  5.36771628e+00,  3.16125078e+01,
           4.45835694e+00,  3.12870918e+01,  2.77870353e+00,
           9.65739488e+01,  1.09097417e+00,  1.25095591e+00,
          -2.32124805e-01,  1.63680326e+02,  3.93607907e+01,
           3.95458534e+01,  1.56957492e+02]],

        [[ 8.61365791e+00,  1.06049452e+01,  1.35165153e+00,
          -5.24408999e+00,  3.79202432e+00,  3.33374856e+01,
          -1.48332684e+00,  3.13173383e+01,  2.42918987e+00,
           9.53236396e+01,  1.54297098e+00,  1.35009681e+00,
           1.55472126e-03,  3.52824896e+01,  3.31210468e+01,
           4.50088329e+01,  1.92817840e+02]],

        [[ 8.84311432e+00,  1.06245653e+01,  5.22546546e-01,
          -1.09252384e+00,  3.10285629e+00,  3.24701028e+01,
           1.23054462e+00,  2.99486012e+01,  2.20443449e+00,
           9.30349732e+01,  3.66452583e-01,  2.81485981e-01,
           2.41060566e-01,  2.85373511e+01,  1.10685799e+01,
           9.13987873e+00,  3.82321127e+01]],

        [[ 8.94028810e+00,  1.07121345e+01,  9.21306183e-01,
          -2.24388098e+00,  4.55606368e+00,  3.41062679e+01,
          -9.54278374e-01,  2.97998154e+01,  2.04940115e+00,
           9.46080580e+01,  1.20830321e+00,  5.52638769e-01,
           3.68667414e-01,  8.94204369e+01,  3.20854788e+01,
           1.88484459e+01,  7.49414209e+01]],

        [[ 9.19856597e+00,  1.13550063e+01,  1.30779278e+00,
          -3.30989993e+00, -1.30336299e-01,  3.36293053e+01,
           2.06461701e-01,  2.94821676e+01,  1.96755339e+00,
           9.34730876e+01,  2.56143933e+00,  8.10127407e-01,
           4.97665373e-01,  1.22719153e+02,  2.04922522e+01,
           2.72440219e+01,  1.03036891e+02]],

        [[ 1.06574748e+01,  1.28788983e+01,  1.46589283e+00,
          -4.36313210e+00,  3.28103470e+00,  3.52590048e+01,
          -3.34315963e+00,  2.89283444e+01,  1.67347796e+00,
           9.40066959e+01,  3.26227721e+00,  9.53345796e-01,
           5.12547036e-01,  2.76026572e+01,  7.57717124e+00,
           3.36140240e+01,  1.22825644e+02]],

        [[ 1.09857344e+01,  1.30157203e+01,  8.25402963e-01,
          -8.85062942e-01,  8.32051317e-01,  3.54405925e+01,
           1.77347434e+00,  2.93488103e+01,  1.48633455e+00,
           9.41213712e+01,  3.49697899e-01,  1.02329436e-01,
           7.23073527e-01,  7.15110835e+01,  1.71739077e+01,
           3.62661584e+00,  9.90428787e+00]],

        [[ 1.11192707e+01,  1.32129000e+01,  1.35328073e+00,
          -1.86920143e+00,  7.73167681e-01,  3.50894306e+01,
           1.60183704e-01,  2.88812542e+01,  1.46136644e+00,
           9.34259171e+01,  1.37112912e+00,  3.06797668e-01,
           1.04648306e+00, -1.72356069e+01,  3.23663027e+01,
           1.07653555e+01,  2.13154038e+01]],

        [[ 1.10790430e+01,  1.31230952e+01,  1.60822837e+00,
          -2.83677315e+00,  1.96737849e-01,  3.50649927e+01,
           2.46618254e+00,  2.95148415e+01,  1.54034394e+00,
           9.51995451e+01,  2.39655012e+00,  5.17559896e-01,
           1.09066847e+00,  4.61208671e+01,  4.02593129e+01,
           1.81482339e+01,  3.08157012e+01]],

        [[ 1.11287735e+01,  1.32345289e+01,  1.72018932e+00,
          -3.81266844e+00,  2.06902359e+00,  3.59038785e+01,
           1.33300510e+00,  3.00030241e+01,  1.40583275e+00,
           9.23724718e+01,  4.33578978e+00,  8.43891790e-01,
           8.76297528e-01, -5.66023597e+01,  1.80463491e+01,
           3.02989883e+01,  5.53562516e+01]],

        [[ 1.12508600e+01,  1.31816229e+01,  7.15619901e-01,
          -9.74777068e-01,  7.95988958e-01,  3.51882176e+01,
           2.50934388e+00,  2.99048163e+01,  1.37113138e+00,
           9.28897051e+01,  3.42307469e-02,  1.01132869e-01,
           6.14487032e-01,  4.67682039e+01,  5.70833024e+01,
           3.55868539e+00,  7.76861021e+00]],

        [[ 1.13246045e+01,  1.31603330e+01,  1.58268245e+00,
          -2.07134489e+00,  5.92545675e-01,  3.54761417e+01,
           1.04898607e+00,  3.02863134e+01,  1.39604619e+00,
           9.39892663e+01,  1.44998978e+00, -9.70760243e-02,
           1.67975847e+00, -7.73435660e+01,  1.74305890e+01,
          -3.44388280e+00, -7.48011344e+00]],

        [[ 1.15319800e+01,  1.36045009e+01,  2.27320704e+00,
          -3.19899333e+00,  1.30233213e+00,  3.55979316e+01,
           2.31307891e-01,  3.00689836e+01,  1.36716354e+00,
           9.50674047e+01,  3.47464372e+00, -7.22098121e-02,
           2.34541686e+00, -8.30850077e+01,  2.76014436e+01,
          -2.57051995e+00, -7.11776974e+00]],

        [[ 1.13209101e+01,  1.33836302e+01,  2.28222259e+00,
          -4.33959517e+00,  3.65079031e+00,  3.57369787e+01,
           4.05468769e-01,  2.92412927e+01,  1.27766829e+00,
           9.31913604e+01,  5.38156522e+00,  1.81933508e-01,
           2.10028908e+00, -3.02514039e+01,  3.23632445e+01,
           6.50175390e+00,  2.17938791e+01]]]),
 array([[[ 1.12506633e+01,  1.31403042e+01,  6.65633993e-01,
          -1.13549460e+00,  8.80747348e-01,  3.55828828e+01,
           1.70896320e+00,  2.93542373e+01,  1.21401019e+00,
           9.43237401e+01, -4.29356961e-02, -1.07035709e-02,
           6.76337564e-01, -3.33196735e+01,  2.67002477e+01,
          -3.80863910e-01, -1.15363678e+00]],

        [[ 1.08041138e+01,  1.26268969e+01,  1.33784311e+00,
          -2.33009819e+00,  1.79730978e+00,  3.48193070e+01,
           2.28193891e+00,  2.88610711e+01,  1.10522844e+00,
           9.37285346e+01,  1.98860984e+00, -1.08413690e-02,
           1.34868447e+00,  7.29516093e+01,  3.30851426e+01,
          -3.77488955e-01, -8.94271334e-01]],

        [[ 1.17167941e+01,  1.36621722e+01,  1.97378864e+00,
          -3.47901618e+00,  3.02153348e+00,  3.51274348e+01,
           2.82971435e+00,  2.90622596e+01,  1.09961553e+00,
           9.32659385e+01,  3.71335037e+00,  1.27758948e-01,
           1.84602969e+00, -6.30306165e+01,  2.35243137e+01,
           4.48784413e+00,  9.77452452e+00]],

        [[ 1.16845177e+01,  1.40226009e+01,  2.15443091e+00,
          -4.76444296e+00, -2.34541560e-01,  3.60069052e+01,
          -2.21347153e+00,  2.91989720e+01,  1.10382945e+00,
           9.04211758e+01,  7.62312431e+00,  1.27443426e-01,
           2.02698749e+00,  7.01472838e+01,  4.99006721e+01,
           4.58884337e+00,  9.80635828e+00]],

        [[ 1.15709537e+01,  1.37210439e+01,  5.48465707e-01,
          -1.03534396e+00, -1.84124989e-01,  3.42858121e+01,
           3.72323760e+00,  2.88916705e+01,  1.08268820e+00,
           9.11598053e+01,  1.21098458e+00,  5.46324205e-02,
           4.93833287e-01,  5.10588858e-01, -7.74638837e+01,
           1.87311690e+00,  5.39644980e+00]],

        [[ 1.19474508e+01,  1.36755936e+01,  7.35496552e-01,
          -1.88746336e+00,  2.09092778e+00,  3.49067033e+01,
           4.19662382e+00,  3.00215800e+01,  1.11075936e+00,
           9.09957891e+01,  3.17098674e+00,  3.33319551e-01,
           4.02177002e-01, -4.17739981e+01, -3.97728549e+01,
           1.16350867e+01,  2.95996605e+01]],

        [[ 1.38036573e+01,  1.57308187e+01,  1.26001403e+00,
          -2.56993659e+00,  3.01219129e+00,  3.60525585e+01,
           8.82246672e-01,  3.03659533e+01,  1.00023413e+00,
           9.20645849e+01,  4.52814404e+00,  4.34292204e-01,
           8.25721824e-01, -1.11952603e+02,  4.17628149e+01,
           1.56573451e+01,  6.16429677e+01]]]),
 array([[[ 1.35565997e+01,  1.55040378e+01,  1.46205814e+00,
          -3.14793901e+00,  3.72346546e+00,  3.63851932e+01,
           1.86316539e+00,  3.00964772e+01,  9.00245246e-01,
           9.06446853e+01,  5.38199532e+00,  5.46647831e-01,
           9.15410306e-01,  3.26161823e+01,  2.39892198e+01,
           1.98898869e+01,  1.39129759e+02]],

        [[ 1.35339391e+01,  1.53027180e+01,  5.92917564e-01,
          -5.49531141e-01,  1.88275645e+00,  3.56272969e+01,
           3.90306238e+00,  3.00539468e+01,  8.46281606e-01,
           9.11770645e+01,  5.85733021e-01,  7.07218301e-02,
           5.22195734e-01,  4.28690172e+00,  3.28064096e+01,
           2.51962764e+00,  2.67760829e+01]],

        [[ 1.37773606e+01,  1.55133406e+01,  1.25894166e+00,
          -1.04702029e+00,  2.47299493e-01,  3.54029453e+01,
           2.96030271e+00,  3.06729229e+01,  9.02417953e-01,
           9.14223526e+01,  8.83973620e-01,  8.19523702e-02,
           1.17698929e+00, -5.24275285e+01,  5.89612388e+01,
           2.90135527e+00,  3.94004046e+01]],

        [[ 1.37673850e+01,  1.50852799e+01,  1.84478550e+00,
          -1.51995226e+00,  1.87327465e+00,  3.48376635e+01,
           3.52683233e+00,  3.06730843e+01,  8.33139346e-01,
           9.13222446e+01,  1.11349266e+00,  1.08245611e-01,
           1.73653989e+00, -3.54162856e+01,  2.13294737e+01,
           3.77102417e+00,  6.43676116e+01]],

        [[ 1.34041048e+01,  1.47411330e+01,  2.16666461e+00,
          -2.10847123e+00,  2.29933688e+00,  3.49177049e+01,
          -1.82302299e-01,  2.99977616e+01,  7.80423212e-01,
           9.09126334e+01,  1.31902384e+00,  1.63443909e-01,
           2.00322070e+00,  6.46913184e+01,  6.52610471e+01,
           5.70708618e+00,  1.06357258e+02]],

        [[ 1.32761194e+01,  1.44580373e+01,  6.38903743e-01,
          -7.25121696e-01, -8.62846405e-01,  3.34787005e+01,
           2.76469686e+00,  2.98139316e+01,  8.12129951e-01,
           9.09803354e+01, -4.93775457e-01,  5.99512284e-02,
           5.78952514e-01, -4.63750800e+01,  5.97529077e-01,
           2.00708922e+00,  3.71913633e+01]],

        [[ 1.31224829e+01,  1.39189524e+01,  1.28637689e+00,
          -1.56016141e+00, -7.45565259e-01,  3.19967429e+01,
           3.01596955e+00,  2.95740678e+01,  8.84916314e-01,
           9.01953964e+01, -1.01575159e+00,  2.50073998e-01,
           1.03630289e+00, -2.64240436e+00,  5.79483528e+01,
           8.00155341e+00,  1.36594518e+02]],

        [[ 1.28676192e+01,  1.38195686e+01,  1.83332445e+00,
          -2.71793227e+00, -1.37882531e+00,  3.05321930e+01,
           2.82661715e+00,  2.94237938e+01,  9.00659970e-01,
           9.15089926e+01, -9.62541982e-01,  2.65458510e-01,
           1.56786594e+00,  3.80850198e+01,  2.43438873e+01,
           8.10503047e+00,  1.12116887e+02]]]),
 array([[[7.49080028]],

        [[7.38139948]],

        [[7.33113764]],

        [[7.40306109]],

        [[6.97321603]],

        [[6.68979596]],

        [[6.87881889]],

        [[6.67738014]],

        [[6.82968008]],

        [[6.5271559 ]],

        [[6.61899118]],

        [[6.78750388]],

        [[6.82751717]],

        [[6.82962146]],

        [[6.63283328]],

        [[6.64646967]],

        [[6.67057088]],

        [[6.48666757]],

        [[6.62653489]],

        [[6.85900765]],

        [[6.6318441 ]]]),
 array([[[6.56434053]],

        [[6.27070574]],

        [[6.29915886]],

        [[6.63525685]],

        [[6.23923467]],

        [[6.3890891 ]],

        [[6.53660298]]]),
 array([[[6.42157066]],

        [[6.12282745]],

        [[6.25114261]],

        [[6.02094135]],

        [[5.96203166]],

        [[5.5946284 ]],

        [[5.34394204]],

        [[5.3809536 ]]]))

In [20]:
def fss_date(df, feature_col, bank_name): # 
    df['date'] = pd.to_datetime(df['year.code'].astype(str) + df['month.code'].astype(str), format='%Y%m') 

    df = df[feature_col]
    df = df.replace([np.inf, -np.inf], np.nan)  # "inf" 값을 NaN으로 대체
    df = df.dropna()
    print(df)
    df = df[df['bank.code'] == bank_name]
    df = df.drop(columns=['bank.code'])
    
    return df

def lstm_train_test(df, target, feature):
    
    '''
    Example of target & feature
    feature = ['KV002','KV003','KV004','KV005','KV006','KV007','KV008','KV009','KV010',
               'KV011', 'KV012', 'KV013','KV014','KV015','KV016','KV017','KV018']
    target = ['KV001']
    '''
    ## feature or label
    feature_df = pd.DataFrame(df, columns=feature)
    label_df = pd.DataFrame(df, columns=target)

    feature_df = feature_df.to_numpy()
    label_df = label_df.to_numpy()
    
    num_feature = len(feature)
    
    
    x_train, x_test, y_train, y_test = train_test_split(feature_df, label_df, test_size=0.4, shuffle=False, random_state=42)
    x_val, x_test, y_val, y_test = train_test_split(x_test, y_test, test_size=0.5, shuffle=False, random_state=42)

    print(f'# of train : {len(x_train)} \n# of val : {len(x_val)} \n# of test : {len(x_test)}')
    
    return x_train.reshape(-1,1,num_feature), x_val.reshape(-1,1,num_feature), x_test.reshape(-1,1,num_feature), y_train.reshape(-1,1,1), y_val.reshape(-1,1,1), y_test.reshape(-1,1,1)


def lstm_model(df,target,feature): 
    ## data prep
    x_train, x_val, x_test, y_train, y_val, y_test = lstm_train_test(df,target,feature)
    
    ## lstm model
    model = Sequential()
    model.add(LSTM(50, activation='relu', input_shape=(1,time_stemp)))
    model.add(Dense(1))
    model.compile(optimizer='adam', loss='mse')
    model.fit(x_train, y_train,
              validation_data=(x_val, y_val),
              epochs=50,
              batch_size=1)
    
    ## hp tuning
    
    return None
    
    
    

df_lstm = fss_date(df, feature_all, 'BANK #1')
x_train, x_val, x_test, y_train, y_val, y_test = lstm_train_test(df=df_lstm, target=feature_target,feature=feature_cols)

        KV001      KV002      KV003     KV004     KV005     KV006      KV007  \
15   7.490800  11.230069  12.892386  0.647280 -8.069694  4.787695  29.034507
16   7.381399  11.509397  12.977475  0.495335 -1.847013  0.894125  29.547321
17   7.331138  11.553702  13.024878  0.820232 -3.768500  2.526414  29.872508
18   7.403061  11.589960  13.047304  1.212506 -5.585090  4.531546  31.057246
19   6.973216   9.064114  10.816283  1.009559 -7.276591  3.756003  30.998928
..        ...        ...        ...       ...       ...       ...        ...
879  7.382142  10.968299  13.063094  1.878980 -3.793386  0.956893  34.626846
880  7.059718  10.815314  12.733773  0.526592 -1.247132  4.581053  34.833039
881  6.858891  10.665785  12.534142  1.030550 -2.661936  2.664026  34.366872
882  6.840320  10.670107  12.508762  1.514801 -4.543245  1.043397  34.195223
883  6.956038  10.731233  12.599827  1.585924 -7.251555 -1.389545  33.836448

        KV008      KV009     KV010       KV011     KV012     KV013     KV014  \
15  -1.752446  31.547586  4.417577   96.510839  3.108897  3.328412 -2.681132
16   2.671965  32.670500  4.259731   96.682896  0.505023  0.182472  0.312864
17  -0.054115  32.198713  4.223614   95.086961  1.079153  0.713768  0.106465
18   1.154366  32.394182  4.220511   96.365554  1.488744  1.076029  0.136478
19   0.018562  31.168660  3.382929   94.943455  1.498435  1.453273 -0.443714
..        ...        ...       ...         ...       ...       ...       ...
879  1.737244  40.267279  0.986555   99.344673  1.430985  0.555365  1.323615
880  2.200539  39.585022  1.014208   98.568201 -0.531786  0.079552  0.447040
881  2.805829  39.109204  0.898691   96.192528 -1.478574  0.318522  0.712028
882  2.198896  39.358875  0.957222  101.278477 -2.278478  0.369362  1.145439
883  1.244069  39.986061  1.032089   97.976613 -0.277044  0.731703  0.854221

         KV015      KV016      KV017       KV018 bank.code       date
15  -25.238069  24.506420  96.638808   -9.084048   BANK #1 2013-12-01
16    4.506754  21.528201   5.391553    1.164575   BANK #1 2014-03-01
17   28.660505  18.974260  21.322032   15.309219   BANK #1 2014-06-01
18   45.932303  21.164867  33.418492   42.007045   BANK #1 2014-09-01
19  -20.013017  27.607346  45.049917   83.792845   BANK #1 2014-12-01
..         ...        ...        ...         ...       ...        ...
879  86.837924  64.717433  19.230542  358.380380  BANK #17 2021-12-01
880 -61.573850   0.621701   2.771032   51.347226  BANK #17 2022-03-01
881  -3.494356  62.240823  10.946595  186.869317  BANK #17 2022-06-01
882  50.944604  27.264489  12.630425  174.716676  BANK #17 2022-09-01
883  83.424289  29.947053  24.758217  192.099002  BANK #17 2022-12-01

[567 rows x 20 columns]
21 7 8
# of train : 21
# of val : 7
# of test : 8

In [31]:
import keras_tuner

(x, y), (x_test, y_test) = keras.datasets.mnist.load_data()

x_train = x[:-10000]
x_val = x[-10000:]
y_train = y[:-10000]
y_val = y[-10000:]

x_train = np.expand_dims(x_train, -1).astype("float32") / 255.0
x_val = np.expand_dims(x_val, -1).astype("float32") / 255.0
x_test = np.expand_dims(x_test, -1).astype("float32") / 255.0

num_classes = 10
y_train = keras.utils.to_categorical(y_train, num_classes)
y_val = keras.utils.to_categorical(y_val, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

In [36]:
from keras import layers

def build_model(hp):
    model = keras.Sequential()
    model.add(layers.Flatten())
    # Tune the number of layers.
    for i in range(hp.Int("num_layers", 1, 3)):
        model.add(
            layers.Dense(
                # Tune number of units separately.
                units=hp.Int(f"units_{i}", min_value=32, max_value=512, step=32),
                activation=hp.Choice("activation", ["relu", "tanh"]),
            )
        )
    if hp.Boolean("dropout"):
        model.add(layers.Dropout(rate=0.25))
    model.add(layers.Dense(10, activation="softmax"))
    learning_rate = hp.Float("lr", min_value=1e-4, max_value=1e-2, sampling="log")
    model.compile(
#         optimizer=keras.optimizers.Adam(learning_rate=learning_rate),
        optimizer=keras.optimizers.legacy.Adam(learning_rate=learning_rate), # for mac
        loss="categorical_crossentropy",
        metrics=["accuracy"],
    )
    return model

tuner = keras_tuner.RandomSearch(
    hypermodel=build_model,
    objective="val_accuracy",
    max_trials=3,
    executions_per_trial=2,
    overwrite=True,
    directory="my_dir",
    project_name="helloworld",
)

tuner.search_space_summary()

Search space summary
Default search space size: 5
num_layers (Int)
{'default': None, 'conditions': [], 'min_value': 1, 'max_value': 3, 'step': 1, 'sampling': 'linear'}
units_0 (Int)
{'default': None, 'conditions': [], 'min_value': 32, 'max_value': 512, 'step': 32, 'sampling': 'linear'}
activation (Choice)
{'default': 'relu', 'conditions': [], 'values': ['relu', 'tanh'], 'ordered': False}
dropout (Boolean)
{'default': False, 'conditions': []}
lr (Float)
{'default': 0.0001, 'conditions': [], 'min_value': 0.0001, 'max_value': 0.01, 'step': None, 'sampling': 'log'}

In [37]:
import socket
def make_localhost(port):    
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    s.connect(('8.8.8.8', 1))
    local_ip_address = s.getsockname()[0] 
    return f'http://{local_ip_address}:{port}'
linear_port = 8000
XGBoost_port = 8010
lightGBM_port =8020
GBM_port =8030

dashboard(linear_model, run_kwarg={'port':linear_port})
linear_address = f'http://{local_ip_address}:{linear_port}' 

dashboard(XGBoost, run_kwarg={'port':XGBoost_port})
XGBoost_address = f'http://{local_ip_address}:{XGBoost_port}'
 
dashboard(lightGBM, run_kwarg={'port':lightGBM_port})
lightGBM_address = f'http://{local_ip_address}:{lightGBM_port}' 

dashboard(GBM, run_kwarg={'port':GBM_port})
GBM_address = f'http://{local_ip_address}:{GBM+port}'